language: python
python: 3.6

branches: master

install:
    - pip install mkdocs

script: true

before_deploy:
    - mkdocs build --clean
    
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
        branch: master
